[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.6.0"

[[constraint]]
  name = "github.com/machinebox/graphql"
  version = "0.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/prisma/prisma-client-lib-go"

[[constraint]]
  name = "github.com/vektah/gqlparser"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
